server:
  port: 8080
  add .address: 0.0.0.0
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://127.0.0.1:3306/javabe}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
#    locations: classpath:db/migration
#    baseline-on-migrate: true
#    validate-on-migrate: true
#    clean-disabled: true
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chat?authSource=admin
      auto-index-creation: true
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 6000 # in second
  refreshable-duration: 36000 # in seconds
